name: Publish Coupon Pop security module to GitHub Packages

on:
  push:
    branches:
      - main
      - feat/*
    tags:
      - 'v*' # 1. [수정] 'v'로 시작하는 태그가 푸시될 때만 실행

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

        # feature 브랜치에서는 SNAPSHOT 버전을 사용 (예: 0.0.1-feat-branch-SNAPSHOT)
        # 브랜치 이름에서 특수문자 제거 후 사용
      - name: Determine Version
        id: determine_version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" && "${{ github.ref_name }}" =~ ^v(.*)$ ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}" # v1.0.0 -> 1.0.0
          elif [[ "${{ github.ref_type }}" == "branch" ]]; then
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
            VERSION="0.0.1-${BRANCH_NAME}-SNAPSHOT" # 임의의 SNAPSHOT 버전 규칙
          else
            VERSION="0.0.1-UNKNOWN-SNAPSHOT"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish to GitHub Packages
        run: ./gradlew publish -Pversion=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}